# Generated by Django 4.2.1 on 2023-06-02 03:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deepemotion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
