# Generated by Django 4.2.1 on 2023-06-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepemotion', '0002_person_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='createDate',
            field=models.DateTimeField(),
        ),
    ]
