# Generated by Django 4.2.1 on 2023-06-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepemotion', '0003_alter_person_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
